// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	ecr "github.com/aws/aws-sdk-go-v2/service/ecr"
	mock "github.com/stretchr/testify/mock"
)

// ImageRepoAPI is an autogenerated mock type for the ImageRepoAPI type
type ImageRepoAPI struct {
	mock.Mock
}

// CreateRepository provides a mock function with given fields: ctx, params, optFns
func (_m *ImageRepoAPI) CreateRepository(ctx context.Context, params *ecr.CreateRepositoryInput, optFns ...func(*ecr.Options)) (*ecr.CreateRepositoryOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ecr.CreateRepositoryOutput
	if rf, ok := ret.Get(0).(func(context.Context, *ecr.CreateRepositoryInput, ...func(*ecr.Options)) *ecr.CreateRepositoryOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecr.CreateRepositoryOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *ecr.CreateRepositoryInput, ...func(*ecr.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
